apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: military-flights
  namespace: military-tracker
  labels:
    strimzi.io/cluster: military-tracker-kafka
spec:
  partitions: 6
  replicas: 1
  config:
    retention.ms: "86400000"
    cleanup.policy: delete
    min.insync.replicas: "1"
