kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: military-tracker
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 80
        protocol: TCP
      - containerPort: 30090
        hostPort: 9090
        protocol: TCP
      - containerPort: 30300
        hostPort: 3000
        protocol: TCP
      - containerPort: 30880
        hostPort: 8880
        protocol: TCP
      - containerPort: 30561
        hostPort: 5601
        protocol: TCP
  - role: worker
  - role: worker
