apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: military-tracker
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: bWlsaXRhcnl0cmFja2Vy
